[package]
name = "claude-rag"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "build_index"
path = "src/bin/build_index.rs"

[[bin]]
name = "retrieve"
path = "src/bin/retrieve.rs"

[dependencies]
tantivy = "0.22"
walkdir = "2"
textwrap = "0.16"
serde_json = "1"
anyhow = "1"